### ISSUE TITLE
Broken packages has wrong dependencies bounds

### ISSUE THREAD

**Issue by Juanlu001** [conda-forge/poliastro-feedstock#22]
When we released the first conda package of poliastro 0.10.0, we forgot to update the minimum required versions of some dependencies. After we found out, we fixed and released the second version (build number `1`) in https://github.com/conda-forge/poliastro-feedstock/pull/21/.

However, package `0` is still online and it sometimes gets installed by conda.

We should either remove the package, or figure out if this is a more general problem.

**Comment by Juanlu001** [comment]
I suspect this is the root cause of https://github.com/poliastro/poliastro/issues/433, and also a similar problem @wselwood had today (an old version of numba was installed).

**Comment by ocefpaf** [comment]
@Juanlu001 can you let me know if this fixes it:

https://anaconda.org/conda-forge/poliastro/files?version=0.10.0

**Comment by Juanlu001** [comment]
Confirmed that the labelling trick worked:

```
$ conda install "poliastro>=0.10" "scipy<1.0"
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - poliastro[version='>=0.10'] -> scipy[version='>=1.0']
  - scipy[version='<1.0']
Use "conda info <package>" to see the dependencies for each package.

```

Thanks @ocefpaf and closing!
