### ISSUE TITLE
Some tests failing

### ISSUE THREAD

**Issue by astrojuanlu** [conda-forge/poliastro-feedstock#30]
See https://github.com/numba/numba-integration-testing/pull/25. My theory:

> I suspect that the failing tests are because recent updates in NumPy and Plotly that were not properly prevented with upper bounds in the poliastro feedstock.

**Comment by Juanlu001** [comment]
Link to build: https://circleci.com/gh/numba/numba-integration-testing/1274

**Comment by Juanlu001** [comment]
There is one test failing in 0.13.1, I suspect because the JPL HORIZONS solution changed again, see #33.

**Comment by astrojuanlu** [comment]
Closing in favor of #19.
